### ISSUE TITLE
Meta tags not added after building gatsby project

### ISSUE THREAD

**Issue by progexplorer24** [spences10/react-seo-component#76]
**Describe the bug**

Hi,
I run into problems when I'm trying to configure SEO component into my project. I'm trying to recreate a blog based on this tutorial: https://www.freecodecamp.org/news/build-a-developer-blog-from-scratch-with-gatsby-and-mdx/
After running gatsby build & gatsby serve meta tags are not added. I'd be grateful for any clues about what may be the reason for this behaviour.

**To Reproduce**

Here's the example repo: 
https://github.com/progexplorer24/blog-template

**Expected behavior**

I expect meta-tags to be added to my blogPostPage and to my main page.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Browser Chromium
 - Version 80

**Comment by progexplorer24** [comment]
Issue solved.
It turned out that the service worker was the problem. 

My source code was loaded from service worker so the data I saw in the view source was different from actual data. When I inspected files inside the build folder it turned out that head tags are all added as expected.

**Comment by spences10** [comment]
Hey @progexplorer24! 

Glad you worked it out, thanks for the issue and the detail you went to :pray: 

The guide you're following was by me too and why this component was built in the first place :upside_down_face: 

Thanks :+1:
